from __future__ import annotations

NBA_DIVISIONS = {
    "ATL": ("East", "Southeast"),
    "BOS": ("East", "Atlantic"),
    "BKN": ("East", "Atlantic"),
    "CHA": ("East", "Southeast"),
    "CHI": ("East", "Central"),
    "CLE": ("East", "Central"),
    "DET": ("East", "Central"),
    "IND": ("East", "Central"),
    "MIA": ("East", "Southeast"),
    "MIL": ("East", "Central"),
    "NYK": ("East", "Atlantic"),
    "ORL": ("East", "Southeast"),
    "PHI": ("East", "Atlantic"),
    "TOR": ("East", "Atlantic"),
    "WAS": ("East", "Southeast"),
    "DAL": ("West", "Southwest"),
    "DEN": ("West", "Northwest"),
    "GSW": ("West", "Pacific"),
    "HOU": ("West", "Southwest"),
    "LAC": ("West", "Pacific"),
    "LAL": ("West", "Pacific"),
    "MEM": ("West", "Southwest"),
    "MIN": ("West", "Northwest"),
    "NOP": ("West", "Southwest"),
    "OKC": ("West", "Northwest"),
    "PHX": ("West", "Pacific"),
    "POR": ("West", "Northwest"),
    "SAC": ("West", "Pacific"),
    "SAS": ("West", "Southwest"),
    "UTA": ("West", "Northwest"),
}
