from __future__ import annotations

NHL_DIVISIONS = {
    "BOS": ("East", "Atlantic"),
    "BUF": ("East", "Atlantic"),
    "DET": ("East", "Atlantic"),
    "FLA": ("East", "Atlantic"),
    "MTL": ("East", "Atlantic"),
    "OTT": ("East", "Atlantic"),
    "TBL": ("East", "Atlantic"),
    "TOR": ("East", "Atlantic"),
    "CAR": ("East", "Metropolitan"),
    "CBJ": ("East", "Metropolitan"),
    "NJD": ("East", "Metropolitan"),
    "NYI": ("East", "Metropolitan"),
    "NYR": ("East", "Metropolitan"),
    "PHI": ("East", "Metropolitan"),
    "PIT": ("East", "Metropolitan"),
    "WSH": ("East", "Metropolitan"),
    "ARI": ("West", "Central"),
    "CHI": ("West", "Central"),
    "COL": ("West", "Central"),
    "DAL": ("West", "Central"),
    "MIN": ("West", "Central"),
    "NSH": ("West", "Central"),
    "STL": ("West", "Central"),
    "WPG": ("West", "Central"),
    "ANA": ("West", "Pacific"),
    "CGY": ("West", "Pacific"),
    "EDM": ("West", "Pacific"),
    "LAK": ("West", "Pacific"),
    "SJS": ("West", "Pacific"),
    "SEA": ("West", "Pacific"),
    "VAN": ("West", "Pacific"),
    "VGK": ("West", "Pacific"),
}

# Legacy ARI is replaced with UTA for current team identity.
NHL_DIVISIONS["UTA"] = NHL_DIVISIONS.pop("ARI")

NHL_AIRCRAFT = {
    "CGY": ("Airbus A320", 17.2),
    "EDM": ("Airbus A320", 17.2),
    "MTL": ("Airbus A320", 17.2),
    "OTT": ("Airbus A320", 17.2),
    "TOR": ("Airbus A320", 17.2),
    "VAN": ("Airbus A320", 17.2),
    "SEA": ("Airbus A320", 17.2),
    "WPG": ("Airbus A320", 17.2),
    "ANA": ("Boeing 757", 20.8),
    "COL": ("Boeing 757", 20.8),
    "MIN": ("Boeing 757", 20.8),
    "LAK": ("Boeing 757", 20.8),
    "PHI": ("Boeing 757", 20.8),
    "FLA": ("Boeing 757", 20.8),
    "NYR": ("Boeing 757", 20.8),
    "TBL": ("Boeing 757", 20.8),
    "VGK": ("Boeing 757", 20.8),
    "WSH": ("Boeing 757", 20.8),
    "UTA": ("Boeing 757", 20.8),
    "BOS": ("Boeing 737", 18.4),
    "BUF": ("Boeing 737", 18.4),
    "CAR": ("Boeing 737", 18.4),
    "CHI": ("Boeing 737", 18.4),
    "CBJ": ("Boeing 737", 18.4),
    "DAL": ("Boeing 737", 18.4),
    "NSH": ("Boeing 737", 18.4),
    "NJD": ("Boeing 737", 18.4),
    "NYI": ("Boeing 737", 18.4),
    "STL": ("Boeing 737", 18.4),
    "PIT": ("Boeing 737", 18.4),
    "SJS": ("Boeing 737-700", 18.0),
    "DET": ("MD80", 23.8),
}

NHL_CANADIAN_FORCE_FOUR = {
    ("MTL", "OTT"),
    ("MTL", "TOR"),
    ("OTT", "TOR"),
    ("CGY", "EDM"),
    ("CGY", "VAN"),
    ("EDM", "VAN"),
}
